version: "3.8"
   
services:
    django:
        build: .
        container_name: django
        command: >
                bash -c "python manage.py makemigrations &&
                            python manage.py migrate &&
                            python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DJANGO_SETTINGS_MODULE=sendcloud.settings
        depends_on:
            - pgdb
            - redis
    celery:
        build: .
        command: celery -A sendcloud worker -l INFO
        volumes:
            - .:/usr/src/app
        depends_on:
            - django
            - redis
    celery-beat:
        build: .
        command: celery -A sendcloud beat --loglevel=info
        volumes:
            - .:/code
        depends_on:
            - redis
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
        
volumes:
    pgdata:
